[package]
name = "metw-mailer"
version = "0.0.1"
edition = "2021"

[dependencies]
lettre = { version = "0.11", features = ["tokio1", "tokio1-native-tls"] }
tokio = { version = "1", features = ["full"] }
strfmt = "0.2"
rand = "0.8"
include_dir = "0.7"
dotenv = "0.15"
